// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ArticleContentsDao is the data access object for table article_contents.
type ArticleContentsDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns ArticleContentsColumns // columns contains all the column names of Table for convenient usage.
}

// ArticleContentsColumns defines and stores column names for table article_contents.
type ArticleContentsColumns struct {
	Id           string //
	ArticleId    string //
	MarkdownText string //
	HtmlText     string //
}

//  articleContentsColumns holds the columns for table article_contents.
var articleContentsColumns = ArticleContentsColumns{
	Id:           "id",
	ArticleId:    "article_id",
	MarkdownText: "markdown_text",
	HtmlText:     "html_text",
}

// NewArticleContentsDao creates and returns a new DAO object for table data access.
func NewArticleContentsDao() *ArticleContentsDao {
	return &ArticleContentsDao{
		group:   "default",
		table:   "article_contents",
		columns: articleContentsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ArticleContentsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ArticleContentsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ArticleContentsDao) Columns() ArticleContentsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ArticleContentsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ArticleContentsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ArticleContentsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
