// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ChaptersDao is the data access object for table chapters.
type ChaptersDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns ChaptersColumns // columns contains all the column names of Table for convenient usage.
}

// ChaptersColumns defines and stores column names for table chapters.
type ChaptersColumns struct {
	Id        string //
	BookId    string // 所属文档
	Name      string // 章节名称
	SortNum   string // 排序值，值越大越靠前
	IsActive  string // 是否启用
	CreatedAt string //
	UpdatedAt string //
}

//  chaptersColumns holds the columns for table chapters.
var chaptersColumns = ChaptersColumns{
	Id:        "id",
	BookId:    "book_id",
	Name:      "name",
	SortNum:   "sort_num",
	IsActive:  "is_active",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewChaptersDao creates and returns a new DAO object for table data access.
func NewChaptersDao() *ChaptersDao {
	return &ChaptersDao{
		group:   "default",
		table:   "chapters",
		columns: chaptersColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ChaptersDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ChaptersDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ChaptersDao) Columns() ChaptersColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ChaptersDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ChaptersDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ChaptersDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
