app_name: gf-admin

server:
  address: ":8199"

jwt:
  issuer: gf-admin
  key: gf-admin
  ttl: 3600

database:
  default:
    type:  "mysql"
    host: 127.0.0.1
    port: 3306
    user: root
    pass: a8968640
    name: gf-admin
    debug: true
