// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/service/internal/dao/internal"
)

// articlesDao is the data access object for table articles.
// You can define custom methods on it to extend its functionality as you wish.
type articlesDao struct {
	*internal.ArticlesDao
}

var (
	// Articles is globally public accessible object for table articles operations.
	Articles = articlesDao{
		internal.NewArticlesDao(),
	}
)

// Fill with you ideas below.
