// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/service/internal/dao/internal"
)

// booksDao is the data access object for table books.
// You can define custom methods on it to extend its functionality as you wish.
type booksDao struct {
	*internal.BooksDao
}

var (
	// Books is globally public accessible object for table books operations.
	Books = booksDao{
		internal.NewBooksDao(),
	}
)

// Fill with you ideas below.
