// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/service/internal/dao/internal"
)

// chaptersDao is the data access object for table chapters.
// You can define custom methods on it to extend its functionality as you wish.
type chaptersDao struct {
	*internal.ChaptersDao
}

var (
	// Chapters is globally public accessible object for table chapters operations.
	Chapters = chaptersDao{
		internal.NewChaptersDao(),
	}
)

// Fill with you ideas below.
