// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/service/internal/dao/internal"
)

// uploadLogsDao is the data access object for table upload_logs.
// You can define custom methods on it to extend its functionality as you wish.
type uploadLogsDao struct {
	*internal.UploadLogsDao
}

var (
	// UploadLogs is globally public accessible object for table upload_logs operations.
	UploadLogs = uploadLogsDao{
		internal.NewUploadLogsDao(),
	}
)

// Fill with you ideas below.
