// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Books is the golang structure of table books for DAO operations like Where/Data.
type Books struct {
	g.Meta    `orm:"table:books, do:true"`
	Id        interface{} //
	Name      interface{} // 文档名称
	Slug      interface{} // 唯一标示
	Type      interface{} // 文档类型
	Cover     interface{} // 封面图
	Github    interface{} // GitHub
	Website   interface{} // 官方网站
	SortNum   interface{} // 排序值
	IsActive  interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
