// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Chapters is the golang structure of table chapters for DAO operations like Where/Data.
type Chapters struct {
	g.Meta    `orm:"table:chapters, do:true"`
	Id        interface{} //
	BookId    interface{} // 所属文档
	Name      interface{} // 章节名称
	SortNum   interface{} // 排序值，值越大越靠前
	IsActive  interface{} // 是否启用
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
