// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UploadLogs is the golang structure of table upload_logs for DAO operations like Where/Data.
type UploadLogs struct {
	g.Meta    `orm:"table:upload_logs, do:true"`
	Id        interface{} //
	Url       interface{} //
	Md5       interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
