// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Articles is the golang structure for table articles.
type Articles struct {
	Id          uint        `json:"id"          ` //
	Title       string      `json:"title"       ` //
	CateId      uint        `json:"cateId"      ` //
	Summary     string      `json:"summary"     ` //
	OriginalUrl string      `json:"originalUrl" ` //
	IsPublish   uint        `json:"isPublish"   ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
