// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ArticleContents is the golang structure for table article_contents.
type ArticleContents struct {
	Id           uint   `json:"id"           ` //
	ArticleId    uint   `json:"articleId"    ` //
	MarkdownText string `json:"markdownText" ` //
	HtmlText     string `json:"htmlText"     ` //
}
