// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Books is the golang structure for table books.
type Books struct {
	Id        uint        `json:"id"        ` //
	Name      string      `json:"name"      ` // 文档名称
	Slug      string      `json:"slug"      ` // 唯一标示
	Type      string      `json:"type"      ` // 文档类型
	Cover     string      `json:"cover"     ` // 封面图
	Github    string      `json:"github"    ` // GitHub
	Website   string      `json:"website"   ` // 官方网站
	SortNum   uint        `json:"sortNum"   ` // 排序值
	IsActive  uint        `json:"isActive"  ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
