// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UploadLogs is the golang structure for table upload_logs.
type UploadLogs struct {
	Id        uint64      `json:"id"        ` //
	Url       string      `json:"url"       ` //
	Md5       string      `json:"md5"       ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
